name: icloud-for-linux
version: '0.1'
summary: iCloud for Linux
description: iCloud for Linux

grade: stable
confinement: strict
base: core18

layout:
  /usr/share/qt5:
    bind: $SNAP/usr/share/qt5

apps:
  icloud-for-linux:
    command: icloud-for-linux.launcher
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - x11

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]

  icloud-for-linux-qml:
    after: [desktop-qt5]
    source: .
    plugin: dump
    stage-packages:
      - qmlscene
      - qml-module-qtquick2
      - qml-module-qtwebview
      - qml-module-qtwebengine
    organize:
      icloud-for-linux.launcher: bin/icloud-for-linux.launcher
