name: icloud-for-linux
version: '0.8'
summary: iCloud for Linux
description: iCloud for Linux

grade: stable
confinement: strict
base: core18

layout:
  /usr/share/qt5:
    bind: $SNAP/usr/share/qt5

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]

  icloud-for-linux:
    after: [desktop-qt5]
    source: .
    plugin: qmake
    build-packages:
      - qtdeclarative5-dev
    stage-packages:
      - qmlscene
      - qml-module-qtquick2
      - qml-module-qtquick-controls
      - qml-module-qtquick-window2
      - qml-module-qtwebengine
      - qml-module-qtquick-dialogs

  dump:
    source: dump
    plugin: dump

apps:
  word:
    command: unofficial-webapp-office.launcher "https://www.office.com/launch/word" "Word"
    plugs: &plugs
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - screen-inhibit-control
      - x11
    environment: &environment
      DISABLE_WAYLAND: 1
  outlook:
    command: unofficial-webapp-office.launcher "https://outlook.live.com/mail/0/inbox" "Outlook"
    plugs: *plugs
    environment: *environment
  excel:
    command: unofficial-webapp-office.launcher "https://www.office.com/launch/excel" "Excel"
    plugs: *plugs
    environment: *environment
  powerpoint:
    command: unofficial-webapp-office.launcher "https://www.office.com/launch/powerpoint" "PowerPoint"
    plugs: *plugs
    environment: *environment
  onenote:
    command: unofficial-webapp-office.launcher "https://www.onenote.com/notebooks" "OneNote"
    plugs: *plugs
    environment: *environment
  onedrive:
    command: unofficial-webapp-office.launcher "https://onedrive.live.com/" "OneDrive"
    plugs: *plugs
    environment: *environment
