name: unofficial-office
version: '0.1'
summary: Unofficial Office
description: Unofficial web app wrapper for Office 365

grade: stable
confinement: strict
base: core18

layout:
  /usr/share/qt5:
    bind: $SNAP/usr/share/qt5

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]

  unofficial-office-qml:
    after: [desktop-qt5]
    source: https://github.com/sirredbeard/unofficial-office.git
    plugin: dump
    override-build: |
      sudo chmod +x unofficial-office.launcher
      cp -v unofficial-office.launcher "$SNAPCRAFT_PART_INSTALL"
      cp -vr snap/gui/* "$SNAPCRAFT_PART_INSTALL"
    stage-packages:
      - qmlscene
      - qml-module-qtquick2
      - qml-module-qtquick-window2
      - qml-module-qtwebengine
      - qml-module-qtquick-dialogs
      - libblkid1
      - libbz2-1.0
      - libgcc1
      - libgcrypt20
      - libgpg-error0
      - liblz4-1
      - liblzma5
      - libmount1
      - libpcre3
      - libselinux1
      - libstdc++6
      - libsystemd0
      - libtinfo5
      - libudev1
      - libuuid1
      - zlib1g

apps:
  word:
    command: unofficial-office.launcher "https://www.office.com/launch/word" "Word"
    desktop: word.desktop
    plugs: &plugs
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - screen-inhibit-control
      - x11
    environment: &environment
      DISABLE_WAYLAND: 1
  outlook:
    command: unofficial-office.launcher "https://outlook.live.com/mail/0/inbox" "Outlook"
    desktop: outlook.desktop
    plugs: *plugs
    environment: *environment
  excel:
    command: unofficial-office.launcher "https://www.office.com/launch/excel" "Excel"
    desktop: excel.desktop
    plugs: *plugs
    environment: *environment
  powerpoint:
    command: unofficial-office.launcher "https://www.office.com/launch/powerpoint" "PowerPoint"
    desktop: powerpoint.desktop
    plugs: *plugs
    environment: *environment
  onenote:
    command: unofficial-office.launcher "https://www.onenote.com/notebooks" "OneNote"
    desktop: onenote.desktop
    plugs: *plugs
    environment: *environment
  onedrive:
    command: unofficial-office.launcher "https://onedrive.live.com/" "OneDrive"
    desktop: onedrive.desktop
    plugs: *plugs
    environment: *environment
