name: Push to Snapcraft

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft

    steps:
    - uses: actions/checkout@v1
    - name: Push snap
      env:
        SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
      run: |
        cd docs
        mkdir .snapcraft
        echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
        snapcraft push --release=stable *.snap
