name: Push to Snapcraft

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    container:
      image: snapcore/snapcraft

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        sudo apt-get update
        wget http://ftp.osuosl.org/pub/ubuntu/pool/universe/q/qtwebengine-opensource-src/qml-module-qtwebengine_5.9.5+dfsg-0ubuntu2_amd64.deb
        dpkg -i qml-module-qtwebengine_5.9.5+dfsg-0ubuntu2_amd64.deb
        sudo apt-get install -fy
        snapcraft     
    - name: Push snap
      env:
        SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
      run: 
        cd snap
        mkdir .snapcraft/
        echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
        snapcraft push --release=stable *.snap
