name: Push to Snapcraft

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    container:
      image: snapcore/snapcraft

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        sudo sed -i 's/xenial/bionic/g' /etc/apt/sources.list
        sudo apt update
        sudo apt -y dist-upgrade
        sudo apt-get -y install wget
        snapcraft     
    - name: Push snap
      env:
        SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
      run: 
        echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > snapcraft.cfg
        snapcraft push --release=stable *.snap
